export class Create_OrderEntry{
    Cost:number;
    StoreId:number;
    OrderId:number;
    ItemId:number;
    FullPrice:any;
    PriceSource:any;
    Price:any;
    QuantityOnOrder:any;
    SalesRepId:number;
    Taxable:number;
    DetailId:number;
    Description:string;
    QuantityRtd:any;
    LastUpdated:any;
    Comment:string;
    DiscountReasonCodeId:number;
    ReturnReasonCodeId:number;
    TaxChangeReasonCodeId:number;
    TransactionTime:any;
    IsAddMoney:boolean;
    VoucherId:number;
}